### PR TITLE
Upgrade lodash to v4

### PR DESCRIPTION
**Pull request by redonkulus**

### CODE REVIEW

**Comment by roderickhsiao** [comment]
@redonkulus do you have access to publish this package?

**Comment by 3den** [comment]
I think i can publish

**Comment by redonkulus** [comment]
Thanks @3den. I sent an you an email asking for permission to publish.

**Comment by 3den** [comment]
@redonkulus permission granted :smile: 

Now you can release this and also jsx-test, please let me know if you guys need anything else.

**Comment by redonkulus** [comment]
thanks @3den! @roderickhsiao new version 0.3.2 released.

**Pull request merged**
